### PR TITLE
fix: weight armature generating error since Blender 5.0.0

### LINKED ISSUE #3: [BUG] Weight Armature did not work in Blender 5.1.0
**Describe the bug**
When I was done with bones, pressing "Generate" in "Weight Armature", it generated weight bones wrongly and threw an exception.

**Steps to reproduce behavior**
1. Open Blender 5.1.0.
2. Select an armature, go to "Weight Armature" and press "Generate".
3. Copies of bones appear and throw an exception.

**Expected behavior**
Generating weight armature correctly.

**Screenshots**
Not working, an exception was thrown.

**Logs**
```
Traceback (most recent call last):
  File "C:\Users\26277\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\source-armature-toolkit\ops.py", line 186, in execute
    weight_armature(0)
    ~~~~~~~~~~~~~~~^^^
  File "C:\Users\26277\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\source-armature-toolkit\weight_armature.py", line 12, in weight_armature
    generate_armature("weight", action)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\26277\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\source-armature-toolkit\utils.py", line 2172, in generate_armature
    armature.data.bones[prefix2 + bone2].select = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bone' object has no attribute 'select'
08:50:16.453  bpy.rna          | ERROR Python script error in SAT_OT_weightarmature_create.execute
08:50:16.453  operator         | ERROR Python: Traceback (most recent call last):
                               |   File "C:\Users\26277\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\source-armature-toolkit\ops.py", line 186, in execute
                               |     weight_armature(0)
                               |     ~~~~~~~~~~~~~~~^^^
                               |   File "C:\Users\26277\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\source-armature-toolkit\weight_armature.py", line 12, in weight_armature
                               |     generate_armature("weight", action)
                               |     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                               |   File "C:\Users\26277\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\source-armature-toolkit\utils.py", line 2172, in generate_armature
                               |     armature.data.bones[prefix2 + bone2].select = True
                               |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               | AttributeError: 'Bone' object has no attribute 'select'
```

**Details**:
Blender Version: 5.1.0

Downloaded through...
- [ ] Main branch
- [x] Release

Release/Addon Version: 1.1.0

**Additional context**

### PR DESCRIPTION
**Pull request by MoRanYue**
Fix #3.

### CODE REVIEW

**Comment by MoRanYue** [comment]
@Haggets Could you review this PR?

**Comment by Haggets** [comment]
Sorry for the delay. I will take a look once I'm home

**Review by Haggets — APPROVED** [review]
Apologies for the terrible code of mine btw
